[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Resource-Policy = "same-origin"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'self'; script-src-elem 'self' 'unsafe-inline' https://app.cal.com; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.cal.com https://*.cal.eu; frame-src 'self' https://*.cal.com https://cal.eu https://*.cal.eu;"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
